package com.gianmarco.wowcraft.playerclass;

/**
 * The type of resource a class uses to power their abilities.
 * Each resource has different mechanics inspired by WoW Classic.
 */
public enum ResourceType {
    NONE("None", 0x808080, 0, false),
    MANA("Mana", 0x0000FF, 100, true), // Blue - Regenerates over time
    RAGE("Rage", 0xFF0000, 100, false), // Red - Generated by dealing/taking damage
    ENERGY("Energy", 0xFFFF00, 100, true); // Yellow - Fast regeneration (for future Rogue class)

    private final String displayName;
    private final int color;
    private final int maxValue;
    private final boolean regenerates;

    ResourceType(String displayName, int color, int maxValue, boolean regenerates) {
        this.displayName = displayName;
        this.color = color;
        this.maxValue = maxValue;
        this.regenerates = regenerates;
    }

    public String getDisplayName() {
        return displayName;
    }

    public int getColor() {
        return color;
    }

    public int getMaxValue() {
        return maxValue;
    }

    /**
     * @return true if this resource regenerates passively over time
     */
    public boolean doesRegenerate() {
        return regenerates;
    }

    /**
     * @return true if this resource's max value is calculated from stats (not fixed)
     */
    public boolean hasDynamicMax() {
        return this == MANA;
    }

    public int getColorWithAlpha() {
        return 0xFF000000 | color;
    }
}
